name: 'Next.js bundle analyzer'
inputs:
  workflow-id:
    description: 'Workflow ID containing this step'
  base-branch:
    description: 'Base branch of the repo (master or main)'
    default: master
  working-directory:
    description: 'Directory containing built files'
    default: ''
  size-threshold:
    description: 'Size to mark as too large'
    default: 500
runs:
  using: 'node16'
  main: 'dist/index.js'
